### ISSUE TITLE
Creative Tab is buggy

### ISSUE THREAD

**Issue by VictiniX888** [tattyseal/CompactStorage#14]
Here, have a picture!
![2015-01-15_16 46 52](https://cloud.githubusercontent.com/assets/9777462/5754704/3e312fde-9cd7-11e4-8204-423bae780e00.png)

Name is bugged (not localized?), and there's a little white stuff at the bottom of the tab.

**Comment by tattyseal** [comment]
That does not occur with me (the white). Try using my mod only.

**Comment by VictiniX888** [comment]
The white part seems to only happen when the tab is at the bottom row...
