### ISSUE TITLE
Crash when using hopper to extract items from Compact Chest

### ISSUE THREAD

**Issue by VictiniX888** [tattyseal/CompactStorage#15]
http://pastebin.com/bW9aYw97

The items get pulled into the Hopper, and it doesn't crash if you open the hopper GUI. When you open the chest's GUI, it crashes.

**Comment by VictiniX888** [comment]
And... for some reason I can't reproduce this anymore .-.

**Comment by VictiniX888** [comment]
It happened again.
http://pastebin.com/bzQMwkfv

**Comment by tattyseal** [comment]
https://github.com/tattyseal/CompactStorage/commit/0dde3e9f32b69b10f6b7e252fb5a2acc88e91205
