### ISSUE TITLE
not working with inventory tweeks

### ISSUE THREAD

**Issue by chanzie** [tattyseal/CompactStorage#18]
when hitting r to sort the inventory via inventory tweeks it is not sorting in backpack or with the chest

**Comment by tattyseal** [comment]
I don't support inventory tweaks currently. It will be added soon in the updated.

**Comment by chanzie** [comment]
tyvm great work on it so far :)

**Comment by tattyseal** [comment]
https://github.com/tattyseal/CompactStorage/commit/9fbe86ab101b20ff945016530b637e36c7c5175d
