### ISSUE TITLE
not able to move chest with dolly from JABBA

### ISSUE THREAD

**Issue by chanzie** [tattyseal/CompactStorage#19]
the chest are not movable with the Jabba dolly so if you need to move them its break them and move the items uber fast or risk losing stuff to random visitors to your base

**Comment by tattyseal** [comment]
Can you pickup normal chests with the Dolly from JABBA? If so I will look into fixing it, if not, it is intended behaviour.

**Comment by chanzie** [comment]
yes you can

**Comment by tattyseal** [comment]
https://github.com/tattyseal/CompactStorage/commit/9fbe86ab101b20ff945016530b637e36c7c5175d
