### ISSUE TITLE
Stack splitting(by rmb) nullify reminder part of stack in chest and backups

### ISSUE THREAD

**Issue by alexeik** [tattyseal/CompactStorage#24]
There seems to be an issue with stacks in a chest right clicking to split the stacks end up deleting one of the stacks this would be on a server aswell vanilla chests are not effected by this 

I can confirm the same issue that "Wakingone94" faced. I did not notice what caused the issue, as he did, however I have noticed that literally half my stuff is missing when I dealt with the backpacks. Please fix this as soon as you can. :(

pasted from http://www.curse.com/mc-mods/minecraft/223703-compactstorage#t1:changes

**Comment by alexeik** [comment]
@Override
public ItemStack decrStackSize(int slot, int amount)
{
ItemStack stack = getStackInSlot(slot);
if(stack != null)
{
if(stack.stackSize <= amount)
{
setInventorySlotContents(slot, null);
}
else
{
ItemStack stack2 = stack.splitStack(amount);
}
}
return stack;
}

here
ItemStack itemStackRemoved;
if (itemStackInSlot.stackSize <= count) {
itemStackRemoved = itemStackInSlot;
setInventorySlotContents(slotIndex, null);
} else {
itemStackRemoved = itemStackInSlot.splitStack(count);
if (itemStackInSlot.stackSize == 0) {
setInventorySlotContents(slotIndex, null);
}
}
return itemStackRemoved;
must be smth like this

@Override
public ItemStack decrStackSize(int slot, int amount)
{
ItemStack stack = getStackInSlot(slot);
if(stack != null)
{
ItemStack itemStackRemoved;
if(stack.stackSize <= amount)
{
itemStackRemoved=stack;
setInventorySlotContents(slot, null);
}
else
{
itemStackRemoved = stack.splitStack(amount);
}
}
return itemStackRemoved;
}

**Comment by tattyseal** [comment]
... It will be updated in the next version, this has been said on the Forum Page
