### ISSUE TITLE
How to dupe your items #2 XP

### ISSUE THREAD

**Issue by VictiniX888** [tattyseal/CompactStorage#27]
So, it's really simple. Just follow these steps and you may be well on your way to getting many many ~~diamonds~~ iron!
1. Put 1 of any material in the Chest Builder or a chest
2. Grab another stack of that material
3. Shift-click on that stack of material
4. Congratulations! You just got yourself duplicates of items!

**Comment by EwyBoy** [comment]
Wow, nice feature. Always wanted a mod that lets you dupe items!

**Comment by VictiniX888** [comment]
Forgot to mention, this works with chests as well
