### ISSUE TITLE
[Crate] Dupe bug

### ISSUE THREAD

**Issue by VictiniX888** [tattyseal/CompactStorage#34]
I don't know whether this is intentional, and I also don't know whether I'm using it the right way.

1. Rightclick on Crate Block with item you wanna dupe, which will turn the crate into the item version of the Crate
2. Rightclick with the Crate Item in hand.
3. Yeah.

**Comment by Mark-R-GitHub** [comment]
It is WIP. In the experimental branch. What did you expect? -Tatty from marks pc
